### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Masrur02** [IDEA-Research/Grounded-SAM-2#13]
Hi,
I am trying to run the python grounded_sam2_tracking_demo.py
I am using a NVIDIA RTX 4090. But it is giving me a CUDA out-of-memory issue. Which parameters can be reduced to solve the memory issue? Can you please let me know?

TIA

**Comment by rentainhe** [comment]
> Hi, I am trying to run the python grounded_sam2_tracking_demo.py I am using a NVIDIA RTX 4090. But it is giving me a CUDA out-of-memory issue. Which parameters can be reduced to solve the memory issue? Can you please let me know?
> 
> TIA

Thank you for your reminder. We did indeed overlook the issue of GPU memory consumption before. We will carefully review our code to see if there are any refinements where we can alleviate the high GPU memory usage. @Masrur02

**Comment by Masrur02** [comment]
Is there currently anyway to reduce the GPU memory usage??

TIA

**Comment by rentainhe** [comment]
> Is there currently anyway to reduce the GPU memory usage??
> 
> TIA

We will carefully check this issue when we have some time.

**Comment by rentainhe** [comment]
It only takes me about `11 GB` memory usage by running:

```bash
python grounded_sam2_tracking_demo.py
```

I was wondering if there are any other process occupying your GPU card or the `video file (already transform to images)` is too long

**Comment by rentainhe** [comment]
This is my memory usage

![image](https://github.com/user-attachments/assets/1491f6e3-07ac-48c3-9d78-4d02e190c687)


If you want to further reduce the memory cost, you can try to run `Grounding DINO` on CPU to get the bounding box predictions.

**Comment by vmazi** [comment]
I was getting this also but I have a 3970ti…looks like 8gb vram is definitely not enough

**Comment by vmazi** [comment]
> I was getting this also but I have a 3070ti…looks like 8gb vram is definitely not enough

How can we run grounded Dino on cpu?

**Comment by rentainhe** [comment]
> I was getting this also but I have a 3070ti…looks like 8gb vram is definitely not enough

You can try a smaller SAM 2 model like `sam2_hiera_tiny.pt`

**Comment by rentainhe** [comment]
I will close this issue first as there's no more questions, feel free to reopen it if needed.

**Comment by nkamath5** [comment]
CUDA OOM issues could also be due to the underlying sam2 code. Worth a look:

https://github.com/facebookresearch/sam2/issues/288
https://github.com/facebookresearch/sam2/issues/264
