### ISSUE TITLE
Tracking ID varied

### ISSUE THREAD

**Issue by TheMattBin** [IDEA-Research/Grounded-SAM-2#14]
Hi thanks for the great work! I've tried out the example of continuous tracking with Dino. However, it seems like the tracking ID varied a lot comparing to SAM2 itself. Could I know where I could make it better?

**Comment by rentainhe** [comment]
Yes, tracking newly appearing objects in a video is indeed a challenging issue. We are also exploring the implementation of this and hope to release more effective methods in future updates.
