### ISSUE TITLE
How to divide the road lane

### ISSUE THREAD

**Issue by SUN-zx** [IDEA-Research/Grounded-SAM-2#15]
I had tried some prompt ，such as ‘lane divider’，‘lane_line’，‘road_markings’，but they all contain ground instead of just lane lines。 How can I get a mask that contains only lane lines？

**Comment by rentainhe** [comment]
I think you can try box prompt with text "lane" for road lane tracking, but it depends a lot on the grounding model's capability, which may not be that powerful to detect road line, we will try to improve model's capability in the future

**Comment by SUN-zx** [comment]
OK，Thank you

**Comment by rentainhe** [comment]
You're welcome, we will close this issue, feel free to reopen it if needed.
