### ISSUE TITLE
OOM occurs when adding certain box prompts.

### ISSUE THREAD

**Issue by MrIsland** [IDEA-Research/Grounded-SAM-2#21]
Dear IDEA-Research Team,

I am working on continuity detection in indoor scenes and have been using a video predictor for this task. Specifically, I first tagged each image using RAM and selected the appropriate bounding boxes with GroundingDINO. These bounding boxes were then used as prompts for SAM2.

However, I encountered an Out of Memory (OOM) issue when too many bbox prompts are entered. I would like to ask if there is something wrong with the way I am using this? And if there is a better way to accomplish this continuity detection?

Looking forward for your reply !

Best regards,
Island

**Comment by rentainhe** [comment]
You can try a smaller `SAM 2` model like `sam2_hiera_tiny` or you can only add tags in a few images to reduce the box nums.

**Comment by MrIsland** [comment]
Thanks again for your patience and answers, I have no more questions.
