### ISSUE TITLE
Does Florence2 can predict multiple object in Open Vocabulary Detection and Segmentation mode?

### ISSUE THREAD

**Issue by LiuShihHung** [IDEA-Research/Grounded-SAM-2#23]
Hi, I want to predict multiple category in Florence2 in Open Vocabulary Detection and Segmentation mode, but I found that if my text_input is "car, face, grass", that can't predict precisely. Dose Florence 2 support muti-category detection ? THX!

**Comment by rentainhe** [comment]
When using Florence-2's open-vocabulary detection feature, I noticed that I couldn't separate categories with commas to achieve multi-category detection. It seems like only one category can be input at a time, or each category needs to be sent to Florence-2 for inference separately.

However, you might consider using the `phrase_grounding feature`, where you concatenate all the categories into a single sentence and then let Florence-2 detect the main objects within that sentence.

**Comment by rentainhe** [comment]
@LiuShihHung If you want to detect multi-objects, you can split them using `<and>` in the input text, for example:

```bash
python grounded_sam2_florence2_image_demo.py \
    --pipeline open_vocabulary_detection_segmentation \
    --image_path ./notebooks/images/cars.jpg \
    --text_input "car <and> building"
```
