### ISSUE TITLE
SAM 2 Florence-2 pipeline image

### ISSUE THREAD

**Issue by spped2000** [IDEA-Research/Grounded-SAM-2#31]
Do you have an image of the Grounded SAM 2 + Florence-2 pipeline, similar to the Grounded SAM 2?

**Comment by rentainhe** [comment]
> Do you have an image of the Grounded SAM 2 + Florence-2 pipeline, similar to the Grounded SAM 2?

Hi @spped2000 , You mean the visualization results using `Florence-2 + SAM 2` or the demo image? You can try the following script to get the visualization results:

```bash
python grounded_sam2_florence2_image_demo.py \
    --pipeline object_detection_segmentation \
    --image_path ./notebooks/images/cars.jpg
```

We name it `grounded_sam2_florence2_image_demo` because it's under our Grounded SAM 2 series, the algorithms behind this are `Florence-2 + SAM 2`

**Comment by spped2000** [comment]
> > Do you have an image of the Grounded SAM 2 + Florence-2 pipeline, similar to the Grounded SAM 2?
> 
> Hi @spped2000 , You mean the visualization results using `Florence-2 + SAM 2` or the demo image? You can try the following script to get the visualization results:
> 
> ```shell
> python grounded_sam2_florence2_image_demo.py \
>     --pipeline object_detection_segmentation \
>     --image_path ./notebooks/images/cars.jpg
> ```
> 
> We name it `grounded_sam2_florence2_image_demo` because it's under our Grounded SAM 2 series, the algorithms behind this are `Florence-2 + SAM 2`

I mean something like this
![image](https://github.com/user-attachments/assets/1eac0fe9-1484-4f8c-85e0-3256a192c567)

**Comment by rentainhe** [comment]
> > > Do you have an image of the Grounded SAM 2 + Florence-2 pipeline, similar to the Grounded SAM 2?
> > 
> > 
> > Hi @spped2000 , You mean the visualization results using `Florence-2 + SAM 2` or the demo image? You can try the following script to get the visualization results:
> > ```shell
> > python grounded_sam2_florence2_image_demo.py \
> >     --pipeline object_detection_segmentation \
> >     --image_path ./notebooks/images/cars.jpg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We name it `grounded_sam2_florence2_image_demo` because it's under our Grounded SAM 2 series, the algorithms behind this are `Florence-2 + SAM 2`
> 
> I mean something like this ![image](https://private-user-images.githubusercontent.com/65110113/360827088-1eac0fe9-1484-4f8c-85e0-3256a192c567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDIwNzYsIm5iZiI6MTcyNDQwMTc3NiwicGF0aCI6Ii82NTExMDExMy8zNjA4MjcwODgtMWVhYzBmZTktMTQ4NC00ZjhjLTg1ZTAtMzI1NmExOTJjNTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA4MjkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MzdjZTY4NDc5ZmFmNTRjOGE2YTI0NWRlZGRjMGIzNjY2YWI1ZGE2MTA3NmM4MDI5MjNhZGJlMzY0ZDc4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IiFFgGNeXjmU40i747h-TB0gz5pvMyuZ8oZkHtdSSxY)

Yes, it's the same pipeline, but using Florence-2 instead of Grounding DINO
