### ISSUE TITLE
Can CUDA 12.2 be used for the Grounded-SAM-2

### ISSUE THREAD

**Issue by Masrur02** [IDEA-Research/Grounded-SAM-2#33]
Hi,

Is there any way to use the CUDA 12.2 for the Grounded-SAM-2?

TIA

**Comment by siberianspot** [comment]
Install PyTorch from official CUDA 12.1 index (you’ll see the warning about using CUDA Toolkit 12.2 through the build process later, but it’ll concludes that’s everything should be fine), install additional packages required for groundingdino and SAM2 (use NumPy<2.0.0), clone groundingdino and SAM2 repos, build wheels for both from the Python env where you have PyTorch installed, install wheels.

**Comment by Masrur02** [comment]
Hi
Thanks. The issue is solved.
