### ISSUE TITLE
Segmentation Another Open Vocabulary Model (Object Detection) Results

### ISSUE THREAD

**Issue by sailfish009** [IDEA-Research/Grounded-SAM-2#36]
Hello, I would like to detect objects using another open vocabulary based object detection model(DE-ViT: detect everyting) and segment them with the input. Is this possible and would be great to have an example. 

![devit](https://github.com/user-attachments/assets/06ff7018-19f9-4a8a-a975-b91f2a494bf2)

**Comment by rentainhe** [comment]
> Hello, I would like to detect objects using another open vocabulary based object detection model(DE-ViT: detect everyting) and segment them with the input. Is this possible and would be great to have an example.
> 
> ![devit](https://private-user-images.githubusercontent.com/17582766/361543572-06ff7018-19f9-4a8a-a975-b91f2a494bf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc2MzAsIm5iZiI6MTcyNDcyNzMzMCwicGF0aCI6Ii8xNzU4Mjc2Ni8zNjE1NDM1NzItMDZmZjcwMTgtMTlmOS00YThhLWE5NzUtYjkxZjJhNDk0YmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYmQwN2U2NTBjNmI3OTYxZDBhMTFhMzc5MjlmZThlNDA4YjI4ZGYzMzk2NzQzOTY5YmU5OGIwNWMxYzMwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.egPjJomtp7VQtbNzzwIxpESQ65A9_G7Kh7ORMnAgnkg)

Yes, I think both `Grounded SAM` and `Grounded SAM 2` have the same idea that combining promptable segmentation model with detection model for detection and segmentation, it will also works with `DE-ViT + SAM 2`, but we want to keep our code more clean for community, I think it would be more convenient for you to implement this idea in your local environment.
