### ISSUE TITLE
Why there is a assert?

### ISSUE THREAD

**Issue by numb89757** [IDEA-Research/Grounded-SAM-2#39]
`assert text_input is None, "Text input should not be none when calling object detection pipeline."`
why text_input should be None? May I change the text_input for different prompt word? For example I only want to detect wheel, can I set text_input='wheel'? I've tried this but it didn't work.
```
"""
Pipeline-1: Object Detection + Segmentation
"""
def object_detection_and_segmentation(
    florence2_model,
    florence2_processor,
    sam2_predictor,
    image_path,
    task_prompt="<OD>",
    text_input=None,
    output_dir=OUTPUT_DIR
):
    assert text_input is None, "Text input should not be none when calling object detection pipeline."
    # run florence-2 object detection in demo
    image = Image.open(image_path).convert("RGB")
    results = run_florence2(task_prompt, text_input, florence2_model, florence2_processor, image)
```

**Comment by rentainhe** [comment]
For `Florance-2` detection pipeline, there should be no text input, if you want to detect specific words, you can try its `open vocabulary detection` or `phrase grounding` pipeline

BTW, here's our typo, the assert info should be `Text input should be None when calling object detection pipeline.`

**Comment by rentainhe** [comment]
You can try the following script:

```bash
python grounded_sam2_florence2_image_demo.py \
    --pipeline open_vocabulary_detection_segmentation \
    --image_path ./notebooks/images/cars.jpg \
    --text_input "car <and> building"
```

**Comment by numb89757** [comment]
Thanks.
