### ISSUE TITLE
请问这个报错怎么解决呢    n, h, w = masks.shape ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by shnulailai** [IDEA-Research/Grounded-SAM-2#4]
Traceback (most recent call last):
  File "/mnt/workspace/lailai/segment/Grounded-SAM-2/grounded_sam2_tracking_demo.py", line 123, in <module>
    all_sample_points = sample_points_from_masks(masks=masks, num_points=1)
  File "/mnt/workspace/lailai/segment/Grounded-SAM-2/track_utils.py", line 14, in sample_points_from_masks
    n, h, w = masks.shape
ValueError: too many values to unpack (expected 3)

**Comment by rentainhe** [comment]
可以检查一下masks的输入，打印一下masks的shape，按理来说应该是 (n, h, w) n表示mask数量，如果不是的话可能需要在前面增加一个维度

**Comment by rentainhe** [comment]
Would you like to provide the text prompt you use and the video source for your demo, so we can check this issue more conveniently:

I've successfully run this demo in my env and return the following results (only vis first frame):

![image](https://github.com/user-attachments/assets/ada097e8-17da-4fbd-949c-63d9a541e93f)

**Comment by shnulailai** [comment]
> 可以检查一下masks的输入，打印一下masks的shape，按理来说应该是 (n, h, w) n表示mask数量，如果不是的话可能需要在前面增加一个维度
> 
> 我们在代码中提供了这样的转换:
> 
> ```python
> # convert the mask shape to (n, H, W)
> if masks.ndim == 3:
>     masks = masks[None]
>     scores = scores[None]
>     logits = logits[None]
> elif masks.ndim == 4:
>     masks = masks.squeeze(1)
> ```
> 
> 按理来说不会报这个问题


我把if中的内容注释掉了，弄了个pass，能跑通了，谢谢您

**Comment by shnulailai** [comment]
> 可以检查一下masks的输入，打印一下masks的shape，按理来说应该是 (n, h, w) n表示mask数量，如果不是的话可能需要在前面增加一个维度
> 
> 我们在代码中提供了这样的转换:
> 
> ```python
> # convert the mask shape to (n, H, W)
> if masks.ndim == 3:
>     masks = masks[None]
>     scores = scores[None]
>     logits = logits[None]
> elif masks.ndim == 4:
>     masks = masks.squeeze(1)
> ```
> 
> 按理来说不会报这个问题


我把if中的内容注释掉了，弄了个pass，能跑通了，谢谢您

> Would you like to provide the text prompt you use and the video source for your demo, so we can check this issue more conveniently:
> 
> I've successfully run this demo in my env and return the following results (only vis first frame):
> 
> ![image](https://private-user-images.githubusercontent.com/48727989/356070108-ada097e8-17da-4fbd-949c-63d9a541e93f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODg2MDAsIm5iZiI6MTcyMzA4ODMwMCwicGF0aCI6Ii80ODcyNzk4OS8zNTYwNzAxMDgtYWRhMDk3ZTgtMTdkYS00ZmJkLTk0OWMtNjNkOWE1NDFlOTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAzMzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZjU1MmVjNDZjYWMyMTFhNGM1ZWQ1MTg1YWMzMDg3YzEyMzdhZmIyNjM5YTg5MDgzMDhhZDYxOTJkZWVmZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SkCAkD1r0gFn-OgTQTw2T_XeweSciPaMqnx_Ni1mvLU)

视频比较单一，就是画面中只有一个人走动的视频，因为视频中是我同事，我不方便提供，谢谢您，不过是不是因为单目标的原因，mask打印出来是(1, 960, 540)，经过if中的语句处理后变成了(1, 1, 960, 540），但是我看示例经过if-else语句后还是（n,h,w）三维的，所以我就注释掉if中语句的内容就跑通了，if代码我也没怎么看懂，不知道对后面有没有影响，但是对当前的我提供的照片组是能跑通的，感谢！

**Comment by rentainhe** [comment]
> > 可以检查一下masks的输入，打印一下masks的shape，按理来说应该是 (n, h, w) n表示mask数量，如果不是的话可能需要在前面增加一个维度
> > 我们在代码中提供了这样的转换:
> > ```python
> > # convert the mask shape to (n, H, W)
> > if masks.ndim == 3:
> >     masks = masks[None]
> >     scores = scores[None]
> >     logits = logits[None]
> > elif masks.ndim == 4:
> >     masks = masks.squeeze(1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 按理来说不会报这个问题
> 
> 我把if中的内容注释掉了，弄了个pass，能跑通了，谢谢您
> 
> > Would you like to provide the text prompt you use and the video source for your demo, so we can check this issue more conveniently:
> > I've successfully run this demo in my env and return the following results (only vis first frame):
> > ![image](https://private-user-images.githubusercontent.com/48727989/356070108-ada097e8-17da-4fbd-949c-63d9a541e93f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODg2MDAsIm5iZiI6MTcyMzA4ODMwMCwicGF0aCI6Ii80ODcyNzk4OS8zNTYwNzAxMDgtYWRhMDk3ZTgtMTdkYS00ZmJkLTk0OWMtNjNkOWE1NDFlOTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAzMzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZjU1MmVjNDZjYWMyMTFhNGM1ZWQ1MTg1YWMzMDg3YzEyMzdhZmIyNjM5YTg5MDgzMDhhZDYxOTJkZWVmZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SkCAkD1r0gFn-OgTQTw2T_XeweSciPaMqnx_Ni1mvLU)
> 
> 视频比较单一，就是画面中只有一个人走动的视频，因为视频中是我同事，我不方便提供，谢谢您，不过是不是因为单目标的原因，mask打印出来是(1, 960, 540)，经过if中的语句处理后变成了(1, 1, 960, 540），但是我看示例经过if-else语句后还是（n,h,w）三维的，所以我就注释掉if中语句的内容就跑通了，if代码我也没怎么看懂，不知道对后面有没有影响，但是对当前的我提供的照片组是能跑通的，感谢！

好的好的，我们这边也会检查一下这些接口的使用，正常输出的mask shape是 `(n, h, w)` n表示object number就行
