### ISSUE TITLE
Fine tuning?

### ISSUE THREAD

**Issue by GXcells** [IDEA-Research/Grounded-SAM-2#41]
Hi,

Is there a way to fine tune founding dino? (For example in biology, it may not properly understand some terms on microscopy images, etc)

**Comment by rentainhe** [comment]
Here are two solutions for this issue:

- We've offered our `Prompt Tuning` API for Grounding DINO model here: https://www.deepdataspace.com/playground/ovp, you can try to fine-tune Grounding DINO on your dataset based on this platform

- You can try to fine-tune some open-source open-set grounding model like [MM-Grounding-DINO](https://github.com/open-mmlab/mmdetection/blob/main/configs/mm_grounding_dino/README.md), [YOLO-World](https://github.com/AILab-CVC/YOLO-World) on your own datasets and combine it with SAM or SAM 2 or Medical SAM for detection and segmentation in specific domain.

**Comment by GXcells** [comment]
Great thanks a lot
