### ISSUE TITLE
Missing Python libraries in the Dockerfile

### ISSUE THREAD

**Issue by yassineAlouini** [IDEA-Research/Grounded-SAM-2#46]
It seems those libraries are missing (had to install them once I built and run the Dockerfile):

```bash

# Missing libraries to install as well

RUN python -m pip install opencv-python transformers supervision pycocotools addict yapf timm
```

**Comment by rentainhe** [comment]
Hi @yassineAlouini , sry for not updating the dockerfile, we will update later. Or would you like to propose a new PR for fixing this, we will merge it as soon as possible.

**Comment by rentainhe** [comment]
We've already updated the Docker file, thanks for your issue.

**Comment by yassineAlouini** [comment]
That's great, thanks!

**Comment by xiao10ma** [comment]
是否也需要同步一下without dockers的安装？我也遇到了这些问题 @rentainhe
