### ISSUE TITLE
ValueError: mask must be a 3D np.ndarray with shape (1, H, W), but got shape (1, 1, 1024, 768) when using prompt "shirt" in Grounded SAM 2

### ISSUE THREAD

**Issue by sahal-786** [IDEA-Research/Grounded-SAM-2#5]
When using Grounded SAM 2 to process an image with the prompt "shirt," I encountered a ValueError. The error indicates that the mask must be a 3D np.ndarray with shape (1, H, W), but the provided mask has shape (1, 1, 1024, 768).
`ValueError: mask must be a 3D np.ndarray with shape (1, H, W), but got shape (1, 1, 1024, 768)`

prompt = "shirt."

![02_1E0A0878](https://github.com/user-attachments/assets/90c5c095-c8bf-423e-8853-3593cb36e7ca)

**Comment by rentainhe** [comment]
I will check this issue later, in this case, you should squeeze the tensor to (n, h, w) first

**Comment by rentainhe** [comment]
@sahal-786 We've already fixed this bug with the following changes:

change the following code
```python
if masks.ndim == 3:
    masks = masks[None]
    scores = scores[None]
    logits = logits[None]
if masks.ndim == 4:
    masks = masks.squeeze(1)
```
to:
```python
if masks.ndim == 4:
    masks = masks.squeeze(1)
```

And the segmentation result is as follows:
![grounded_sam2_annotated_image_with_mask](https://github.com/user-attachments/assets/bba13488-cb9a-4904-afb5-514d3a30ceed)

**Comment by rentainhe** [comment]
I will close this issue because the bug has already been fixed, feel free to reopen it if you need any other helps.
