### ISSUE TITLE
returned label differs from original prompt in Grounded-SAM2

### ISSUE THREAD

**Issue by mtablo** [IDEA-Research/Grounded-SAM-2#67]
### Issue
![621000000001](https://github.com/user-attachments/assets/6f04d42a-6c2e-4ba4-815e-8084c88eb267)

Hi, I'm attempting to detect `"a black and white french bulldog"` from the image using Grounded-SAM2.

![image](https://github.com/user-attachments/assets/ec6f4780-042c-4d1f-b4f3-cad77d9b0939)

While the model successfully detects the dog mask, but the `results[0]["labels"]` from the `post_process_grounded_object_detection` function is `"a black french bulldog"`, which differs from the original prompt.

### Question
I want the exact text that was in the original prompt.
How can I ensure that the detected label exactly matches the original prompt text?

**Comment by rentainhe** [comment]
Hi @mtablo , we have some similar discussions here: https://github.com/IDEA-Research/Grounded-SAM-2/issues/50 , you can try the local grounding dino demo and follow our Grounding DINO `specific phrase` inference instructions to achieve this.

**Comment by mtablo** [comment]
thank you! I'll try that!
