### ISSUE TITLE
can you provide a dockerfile,to provide a method to install with docker??

### ISSUE THREAD

**Issue by melodyhappy** [IDEA-Research/Grounded-SAM-2#7]
thx,this code repo needs python 3.10 and cuda 12.1,which a conflict with my current environment！

**Comment by rentainhe** [comment]
We will try to provide docker file for better usage

**Comment by ShuoShenDe** [comment]
Hi~ Dear molodyhappy,

I have provided the docker file in [repository](https://github.com/ShuoShenDe/Grounded-SAM-2), you can check and try this environment, if you encounter any problems, please let me know.

Susan

**Comment by melodyhappy** [comment]
Thank you very much for your help, I have successfully run it now.
