### ISSUE TITLE
In README.md the URL for IDEA research is linked to Meta AI 

### ISSUE THREAD

**Issue by dahyun-kang** [IDEA-Research/Grounded-SAM-2#73]
https://github.com/IDEA-Research/Grounded-SAM-2/blob/de62b7fb0bda7700e66dfeae8eb85deeca86545a/README.md?plain=1#L3

Hello, just realized the affiliation``IDEA research'' in [README.md](https://github.com/IDEA-Research/Grounded-SAM-2/blob/main/README.md?plain=1#L3) is linked to Meta (https://ai.meta.com/research/).
Are these two institutions actually related or is it a mistake?

**Comment by rentainhe** [comment]
Sorry, this is our typo, we will fix it later.
