### ISSUE TITLE
Plans to inegrate newest SAM2 update

### ISSUE THREAD

**Issue by DimitarDimeski** [IDEA-Research/Grounded-SAM-2#75]
Hi there. It's amazing what you have managed to create with this project (both with SAM and SAM2). I have been following this project closely and I know that tracking new objects across videos is something that you have been developing since the start. Last week I noticed that SAM2 got native support for this sort of task. Are there any plans to integrate it into the Grounded SAM 2 tracking pipeline?

**Comment by rentainhe** [comment]
> Hi there. It's amazing what you have managed to create with this project (both with SAM and SAM2). I have been following this project closely and I know that tracking new objects across videos is something that you have been developing since the start. Last week I noticed that SAM2 got native support for this sort of task. Are there any plans to integrate it into the Grounded SAM 2 tracking pipeline?

We are decided to update to the latest sam2 version for better usage

**Comment by DimitarDimeski** [comment]
Excellent. Glad to hear it. Closing the issue.
